<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
    <AssemblyTitle>Comical</AssemblyTitle>
    <Description>Managing and Reading Comics</Description>
    <Company>calbonaler</Company>
    <Product>Comical</Product>
    <Copyright>Copyright © calbonaler 2010-2024</Copyright>
    <AssemblyVersion>4.4.17.0</AssemblyVersion>
    <FileVersion>4.4.17.0</FileVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Resources\Comical.ico</ApplicationIcon>
    <ApplicationManifest>Properties\app.manifest</ApplicationManifest>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <ForceDesignerDPIUnaware>true</ForceDesignerDPIUnaware>
    <RollForward>Major</RollForward>
  </PropertyGroup>
  <ItemGroup>
    <RuntimeHostConfigurationOption Include="System.Globalization.UseNls" Value="true" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DockPanelSuite" Version="3.1.1" />
    <PackageReference Include="DockPanelSuite.ThemeVS2015" Version="3.1.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ComicalCore\ComicalCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>