//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34209
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comical.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comical.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0} All rights reserved. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AboutDialog_CopyrightFormat {
            get {
                return ResourceManager.GetString("AboutDialog_CopyrightFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを追加しています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppendingFile {
            get {
                return ResourceManager.GetString("AppendingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キャンセル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パスワードが適切でないため復号化できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotDecryptBecausePasswordNotProper {
            get {
                return ResourceManager.GetString("CannotDecryptBecausePasswordNotProper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保護の設定(&amp;P) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfigureProtection {
            get {
                return ResourceManager.GetString("ConfigureProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] Cross {
            get {
                object obj = ResourceManager.GetObject("Cross", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   保存しない(&amp;N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DoNotSave {
            get {
                return ResourceManager.GetString("DoNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロードしています {0} 個中 {1} 個完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} への変更内容を保存しますか? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DoYouSaveChanges {
            get {
                return ResourceManager.GetString("DoYouSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像のエクスポート に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExportImages {
            get {
                return ResourceManager.GetString("ExportImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像の抽出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExtractImages {
            get {
                return ResourceManager.GetString("ExtractImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] FreeHand {
            get {
                object obj = ResourceManager.GetObject("FreeHand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Byte[] のローカライズされたリソースを検索します。
        /// </summary>
        internal static byte[] GrispingHand {
            get {
                object obj = ResourceManager.GetObject("GrispingHand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   {0} 個の項目 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageCountStringRepresentation {
            get {
                return ResourceManager.GetString("ImageCountStringRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} x {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageResolutionStringRepresentation {
            get {
                return ResourceManager.GetString("ImageResolutionStringRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} x {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImageSizeStringRepresentation {
            get {
                return ResourceManager.GetString("ImageSizeStringRepresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像をインポートしています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ImportingImages {
            get {
                return ResourceManager.GetString("ImportingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ブックマーク に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InconsistentData_DataTypes_Bookmarks {
            get {
                return ResourceManager.GetString("InconsistentData_DataTypes_Bookmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   画像コレクション に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InconsistentData_DataTypes_Images {
            get {
                return ResourceManager.GetString("InconsistentData_DataTypes_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   矛盾の存在するデータを保存しようとしました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InconsistentData_Instruction {
            get {
                return ResourceManager.GetString("InconsistentData_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   このデータは複数の項目の間で整合性が保持されていません。矛盾の無いようにデータを修正してください。
        ///
        ///矛盾が検出されたデータ: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InconsistentData_Text {
            get {
                return ResourceManager.GetString("InconsistentData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを復号化するパスワードを入力してください(&amp;P): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputPasswordToDecrypt {
            get {
                return ResourceManager.GetString("InputPasswordToDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを暗号化するパスワードを入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputPasswordToEncrypt {
            get {
                return ResourceManager.GetString("InputPasswordToEncrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新しいパスワードを両方のボックスに入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputSamePasswordInBothBox {
            get {
                return ResourceManager.GetString("InputSamePasswordInBothBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Next {
            get {
                object obj = ResourceManager.GetObject("Next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   ファイルを開いています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpeningFile {
            get {
                return ResourceManager.GetString("OpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力したパスワードは一致しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PasswordsNotSame {
            get {
                return ResourceManager.GetString("PasswordsNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        internal static System.Drawing.Bitmap Previous {
            get {
                object obj = ResourceManager.GetObject("Previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   保存する(&amp;S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを検査しています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ScanningFiles {
            get {
                return ResourceManager.GetString("ScanningFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} - {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleFormat {
            get {
                return ResourceManager.GetString("TitleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ツール(&amp;L) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無題 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ここにプレビューを生成します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerDescription_NoSelection {
            get {
                return ResourceManager.GetString("ViewerDescription_NoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 個の画像が選択されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ViewerDescription_Selection {
            get {
                return ResourceManager.GetString("ViewerDescription_Selection", resourceCulture);
            }
        }
    }
}
