//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34014
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comical.Archivers.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comical.Archivers.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   インストールされているアーカイバーはすべて最新版です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AllArchiversAreLatest {
            get {
                return ResourceManager.GetString("AllArchiversAreLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定されたAPI関数 &apos;{0}&apos; が存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ApiFunctionNotFound {
            get {
                return ResourceManager.GetString("ApiFunctionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された書庫 &apos;{0}&apos; が存在しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArchiveNotFound {
            get {
                return ResourceManager.GetString("ArchiveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アーカイバー &apos;{0}&apos; は他の操作を実行中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ArchiverIsBusy {
            get {
                return ResourceManager.GetString("ArchiverIsBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定された書庫 &apos;{0}&apos; は &apos;{1}&apos; では展開できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotExtractArchive {
            get {
                return ResourceManager.GetString("CannotExtractArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DLL を読み込めませんでした。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FailedDllLoading {
            get {
                return ResourceManager.GetString("FailedDllLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インストール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ダウンロードしています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InstallDownloadingDll {
            get {
                return ResourceManager.GetString("InstallDownloadingDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   書庫を展開しています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InstallExtractingArchive {
            get {
                return ResourceManager.GetString("InstallExtractingArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 番目のサーバーからダウンロードしています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InstallRetryMessage {
            get {
                return ResourceManager.GetString("InstallRetryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型パラメータ {0} は {1} の派生型である必要があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TypeParameterMustBeDerivedType {
            get {
                return ResourceManager.GetString("TypeParameterMustBeDerivedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アンインストール に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; を削除できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UninstallCannotRemoveFile {
            get {
                return ResourceManager.GetString("UninstallCannotRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル &apos;{0}&apos; は使用中です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UninstallFileInUse {
            get {
                return ResourceManager.GetString("UninstallFileInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル &apos;{0}&apos; には読み取り専用属性が設定されている可能性があります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UninstallSetReadOnlyAttribute {
            get {
                return ResourceManager.GetString("UninstallSetReadOnlyAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   更新 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
    }
}
